### ISSUE TITLE
binary data not supported

### ISSUE THREAD

**Issue by Ksengine** [Ksengine/WSocket#4]
binary data not supported
add this feature

**Comment by peter-shoes** [comment]
where is binary data not supported?
regardless, why not simply use the built in python methods for binary conversion?
for int to bin: bin(int)
for bin to int: int(bin, 2)

**Comment by Ksengine** [comment]
thanks 
i have no time to do
please help

**Comment by peter-shoes** [comment]
@Ksengine sure! i can do this, just let me know what files/lines you're having trouble, i can't seem to find where you would need this feature.

**Comment by Ksengine** [comment]
https://github.com/Ksengine/WSocket/blob/8f7b973bc961e39eea9999b7c6964eaa5c8465d5/wsocket.py#L246

**Comment by Ksengine** [comment]
i will close this issue  i fixed it.
